services:
  mydb:
    image: mariadb
    ports:
      - 8082:3306
    environment:
      MARIADB_DATABASE: mydb
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mydb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: toor
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  wordpress:
  db:
